---
title: "Bind Constraint"
output: html_notebook
---
```{r}
Y
library(ape)
library(phytools)
```
```{r}
.libPaths()
```



```{r}
mollusk_tree <- read.tree(sub_chiton.tre)
annelid_tree <- read.tree(Struck_2011.tre)
gastro_tree <- read.tree(Giribet_gastro_2019.tre)
```

```{r}
gastro_tree <- drop.tip(gastro_tree, "Chiton_marmoratus")
gastro_tree <- unroot(gastro_tree)
root_G <- root(gastro_tree, outgroup = 1)
plot(gastro_tree,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:gastro_tree$Nnode,node=1:gastro_tree$Nnode+Ntip(gastro_tree))

```


Drop Matching Tips
```{r}
mollusk_tree <- drop.tip(phy = mollusk_tree, tip = c("Helobdella_robusta", "Capitella_teleta"))
annelid_tree <- drop.tip(phy = annelid_tree, tip = c("Crassostrea_gigas","Arenicola_marina","Cerebratulus_lacteus"))

```

```{r}
plot(annelid_tree,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:annelid_tree$Nnode,node=1:annelid_tree$Nnode+Ntip(annelid_tree))
```

```{r}
plot(mollusk_tree,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:mollusk_tree$Nnode,node=1:mollusk_tree$Nnode+Ntip(mollusk_tree))
```


```{r}

root_M <- root(mollusk_tree, outgroup = 27)
root_A <- root(annelid_tree, outgroup = 33)
root_G <- root(gastro_tree, outgroup = 1 )
root_M <- drop.tip(phy = root_M, tip = c("Lingula_anatina", "Phoronis_australis"))
root_A <- drop.tip(phy = root_A, tip = c("Lottia_gigantea", "Crassostrea_gigas"))
root_A_write <- write.tree(root_A, file = "root_A.tre")
root_M_write <- write.tree(root_M, file = "root_M.tre")
root_G_write <- write.tree(root_G, file = "root_G.tre")
plot(root_A)
root_A$tip.label
root_M$tip.label
root_G$tip.label
```


```{r}
tr1 <- root_A
tr2 <- root_G
tr1$tip.label[34]<-"NA"
tr2$root.edge<-0
constraint<-paste.tree(tr1,tr2)
plot(constraint)
constraint_tree <- write.tree(constraint, file = "Struck_Giribet_Con.tre")
```

```{r}
unroot_con <- unroot(constraint)
root_con <- root(unroot_con, outgroup = "Bugula_neritina")
plot(root_con,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:root_con$Nnode,node=1:root_con$Nnode+Ntip(root_con))
root_con <- write.tree(root_con, file = "rooted_constraint")
root_con$tip.label
```

```{r}
sub_chiton <- read.tree ()
plot(sub_chiton,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:sub_chiton$Nnode,node=1:sub_chiton$Nnode+Ntip(sub_chiton))

tr1 <- constraint
tr2 <- sub_chiton
tr1$tip.label[35]<-"NA"
tr2$root.edge<-0
constraint<-paste.tree(tr1,tr2)
plot(constraint)
constraint_tree <- write.tree(constraint, file = "SVG_con.tre")
```




