---
title: "OTL_trees"
output: html_notebook
---

```{r}
library(rotl)
```

```{r}
A_taxa <- tnrs_match_names(names = c("Amphitrite ornata",
"Arenicola cristata",
"Armandia brevis",
"Bimastos rubidus",
"Bonellia viridis",
"Branchiobdella",
"Cambarincola philadelphicus",
"Capitella capitata",
"Capitella teleta",
"Chaetogaster",
"Chaetopterus",
"Clymenella mucosa",
"Clymenella torquata",
"Dinophilus",
"Diopatra cuprea",
"Eisenia fetida",
"Erpobdella",
"Galeolaria caespitosa",
"Glossiphonia",
"Glycera",
"Golfingia",
"Hirudo medicinalis",
"Hydroides elegans",
"Ikedosoma gogoshimense",
"Laeonereis culveri",
"Lepidonotus squamatus",
"Lissomyema",
"Lumbricillus",
"Marenzelleria",
"Myzostomum",
"Neosabellaria",
"Notomastus tenuis",
"Ophryotrocha",
"Owenia fusiformis",
"Pectinaria gouldii",
"Phascolosoma",
"Phyllodoce maculata",
"Phylo foetida",
"Piscicola geometra",
"Platynereis dumerilli",
"Pomatocerus triqueter",
"Proceraea fasciata",
"Pseudopolydora",
"Rhynchelmis",
"Scoloplos armiger",
"Serpula vermicularis",
"Spirorbis spirorbis",
"Sternaspis",
"Sthenelais boa",
"Streblospio benedicti",
"Stylaria lacustris",
"Themiste lageniformis",
"Themiste pyroides",
"Theromyzon",
"Tomopteris",
"Tubifex tubifex",
"Tubificoides",
"Urechis caupo",
"Oxydromus obscurus",
"Lanice conchilega",
"Alvinella pompejana",
"Ophelia limacina",
"Helobdella robusta",
"Haementeria depressa",
"Perionyx excavatus",
"Lumbricus rubellus",
"Eisenia andrei",
"Ridgeia piscesae",
"Flabelligera affinis",
"Cirratulidae",
"Pomatoceros lamarckii",
"Malacoceros fuliginosus",
"Eurythoe complanata",
"Onuphis iridescens",
"Lumbrineris zonata",
"Typosyllis",
"Glyceratri dactyla",
"Eulalia clavigera",
"Sipunculus nudus",
"Myzostoma cirriferum",
"Bugula neritina"
))

A_taxa
#A_taxa
#"Polygordius neapolitanus",
```


```{r}
M_taxa <- tnrs_match_names(names = c("Adalaria",
"Adula californiensis",
"Ancula gibbosa",
"Aplysia californica",
"Aplysia fasciata",
"Armina californica",
"Bankia",
"Bembicium nanum",
"Biomphalaria",
"Bithynia",
"Bulla",
"Busycon",
"Calliostoma",
"Cerastoderma",
"Cavolinia",
"Chiton marmoratus",
"Conuber",
"Conus vexillum",
"Crepidula fornicata",
"Cymbulia",
"Dendronotus",
"Deroceras",
"Doris montereyensis",
"Doto coronata",
"Dreissenidae",
"Elliptio complanata",
"Elysia viridis",
"Epimenia",
"Ercolania",
"Fiona pinnata",
"Firoloida",
"Fusitriton",
"Gibbula",
"Okenia angelica",
"Haliotis",
"Herpetopoma gemmatum",
"Hiatella",
"Ilyanassa obsoleta",
"Lacuna pallidula",
"Lambis truncata",
"Limapontia",
"Lissachatina",
"Littorina",
"Tectura scutum",
"Lymnaea stagnalis",
"Margarites helicinus",
"Marisa cornuarietis",
"Melibe leonina",
"Mercenaria mercenaria",
"Mytilus edulis",
"Onchidoris bilamellata",
"Palio nothus",
"Pandora inaequivalvis",
"Peronia verruculata",
"Petrasma pervernicosa",
"Pholas dactylus",
"Physa fontinalis",
"Pila globosa",
"Pinctada",
"Placopecten",
"Planorbella trivolvis",
"Cochlostoma",
"Pterotrachea",
"Rissoa parva",
"Thylacodes",
"Sinotaia",
"Sphaerium striatinum",
"Spisula solidissima",
"Stenoplax heathiana",
"Stramonita haemastoma",
"Teredo clappi",
"Tonna",
"Tritonia tetraquetra",
"Turbo radiatus",
"Umbraculum umbraculum",
"Viviparus",
"Yoldia",
"Magallana gigas",
"Marsenia",
"Middendorffia",
"Nucella lapillus",
"Patella vulgata",
"Protula tubularia",
"Raphidrilus",
"Theodoxus",
"Tricornis",
"Varohadra",
"Vermetus",
"Cochlostoma elegans",
"Onchidiidae",
"Okenia elegans",
"Facelina bostoniensis",
"Haloa japonica",
"Hermaea bifida",
"Lottia gigantea",
"Lottia scutum",
"Alanbeuella victrix",
"Antalis dentalis",
"Lyncina carneola",
"Cystiscus minutissimus",
"Chaetoderma californicum",
"Falcidens sagittiferus",
"Scutopus ventrolineatus",
"Neomenia megatrapezata",
"Stylomenia sulcodoryata",
"Amphimeniidae",
"Prochaetoderma californicum",
"Lepidozona mertensii",
"Acanthopleura granulata",
"Acanthopleura gemmata",
"Chiton olivaceus",
"Cryptoplax larvaeformis",
"Acanthochitona crinita",
"Nuttallochiton mirandus",
"Mopalia hindsii",
"Katharina tunicata",
"Callochiton",
"Leptochiton asellus",
"Hanleya nagelfar",
"Notospermus geniculatus",
"Euprymna scolopes",
"Laevipilina hyalina",
"Pomacea canaliculata",
"Crassostrea virginica",
"Bathymodiolus platifrons",
"Mizuhopecten yessoensis",
"Scapharca broughtonii",
"Nautilus pompilius",
"Dosidicus gigas",
"Doryteuthis pealeii",
"Octopus vulgaris",
"Solemya velum",
"Ennucula tenuis",
"Anadara trapezia",
"Neotrigonia margaritacea",
"Villosa lienosa", 
"Astarte sulcata",
"Myochama anomioides", 
"Ruditapes philippinarum",
"Graptacme eborea",
"Gadila tolmiei",                 
"Entalina tetragona",          
"Bayerotrochus midas",           
"Granata imbricata",               
"Lepetodrilus pustulosus",        
"Amphiplica gordensis",            
"Haliotis",               
"Phasianella ventricosa",          
"Monodonta labio",                 
"Cellana radiata",                 
"Nacella magelanica",             
"Paralepetopsis",                  
"Eoacmaea pustulata",             
"Patelloida saccharina",           
"Nipponacmea fuscoviridis",       
"Tectura fenestrata",              
"Testudinalia testudinalis",      
"Titiscania limacina",            
"Bathynerita naticoidea",          
"Nerita melanotragus",            
"Smaragdia rangiana",              
"Clithon parvulum",        
"Neritina",                        
"Puperita pupa",                  
"Pleurobranchaea californica",    
"Fiona pinnata",                   
"Bathydoris clavigera",            
"Tylodina fungina",               
"Clione antarctica",               
"Haminoea antillarum",            
"Oxynoe viridis",                  
"Microhedyle glandulifera", 
"Pomacea diffusa",                 
"Oncomelania hupensis",          
"Rubyspiridae",             
"Euspira heros",                  
"Echinolittorina malaccana",       
"Lobatus gigas",                  
"Urosalpinx cinerea",             
"Conus consors",                   
"Crassispira cerithina",          
"Cumia reticulata",                
"Volegalea cochlidium",          
"Charonia tritonis",               
"Bugula neritina"
))

M_taxa
#"Myosotella ?","Siphonaria pectinata","Carychium tridentata","Dreissena polymorpha",
```

```{r}
tree <- tol_induced_subtree(ott_ids = ott_id(A_taxa))
write_A <- write.tree(tree, file = "~/Desktop/otl_A_tree.tre")
plot(tree, cex = .8, label.offset = .1, no.margin = TRUE)
library(ape)
plot(tree,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:tree$Nnode,node=1:tree$Nnode+Ntip(tree))
```

```{r}
tree_M <- tol_induced_subtree(ott_ids = ott_id(M_taxa))
write_M <- write.tree(tree_M, file = "~/Desktop/otl_M_tree.tre")
plot(tree_M, cex = .8, label.offset = .1, no.margin = TRUE)

plot(tree_M,no.margin=TRUE,edge.width=2,cex=0.7)
nodelabels(text=1:tree_M$Nnode,node=1:tree_M$Nnode+Ntip(tree_M))
```







